# Generated by Django 4.1.5 on 2023-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('email', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
